import EuclideanSplit
import PivotDirections
import CapCover

/-!
# Actual hairbrush plane bins and their overlap away from the stem

An orthogonal frame identifies the fixed stem coordinate and its Euclidean
transverse complement. A plane bin is the actual affine plane generated by that
stem and one unoriented unit transverse vector, thickened by a specified width.
-/
namespace KakeyaFormal.HairbrushPlanes

open KakeyaFormal.EuclideanSplit KakeyaFormal.PivotDirections KakeyaFormal.ProjectiveGeometry

noncomputable section

def transverseCoordinate {k : ℕ} (frame : Space (k+1) ≃ₗᵢ[ℝ] Space (k+1))
    (x : Space (k+1)) : Space k := tail (frame x)

@[simp] theorem transverseCoordinate_add {k : ℕ} (f : Space (k+1) ≃ₗᵢ[ℝ] Space (k+1))
    (x y : Space (k+1)) : transverseCoordinate f (x+y) = transverseCoordinate f x+transverseCoordinate f y := by
  simp [transverseCoordinate]

@[simp] theorem transverseCoordinate_sub {k : ℕ} (f : Space (k+1) ≃ₗᵢ[ℝ] Space (k+1))
    (x y : Space (k+1)) : transverseCoordinate f (x-y) = transverseCoordinate f x-transverseCoordinate f y := by
  simp [transverseCoordinate]

@[simp] theorem transverseCoordinate_smul {k : ℕ} (f : Space (k+1) ≃ₗᵢ[ℝ] Space (k+1))
    (a : ℝ) (x : Space (k+1)) : transverseCoordinate f (a • x) = a • transverseCoordinate f x := by
  simp [transverseCoordinate]

@[simp] theorem transverseCoordinate_zero {k : ℕ} (f : Space (k+1) ≃ₗᵢ[ℝ] Space (k+1)) :
    transverseCoordinate f 0 = 0 := by simp [transverseCoordinate]

theorem transverseCoordinate_norm_le {k : ℕ} (f : Space (k+1) ≃ₗᵢ[ℝ] Space (k+1))
    (x : Space (k+1)) : ‖transverseCoordinate f x‖ ≤ ‖x‖ := by
  exact (tail_norm_le (f x)).trans (le_of_eq (f.norm_map x))

/-- The actual thickened affine plane in these orthogonal coordinates. -/
def plank {k : ℕ} (frame : Space (k+1) ≃ₗᵢ[ℝ] Space (k+1))
    (origin : Space (k+1)) (normal : Space k) (width : ℝ) : Set (Space (k+1)) :=
  {x | ∃ b : ℝ, ‖transverseCoordinate frame (x-origin)-b • normal‖ ≤ width}

/-- This transverse definition is exactly proximity to an actual affine plane
spanned by the stem coordinate and the transverse representative. -/
theorem plank_iff_affine_plane {k : ℕ} (f : Space (k+1) ≃ₗᵢ[ℝ] Space (k+1))
    (origin x : Space (k+1)) (w : Space k) (width : ℝ) :
    x ∈ plank f origin w width ↔ ∃ a b : ℝ,
      ‖x-(origin+f.symm (cons a (b • w)))‖ ≤ width := by
  constructor
  · rintro ⟨b,hb⟩
    refine ⟨head (f (x-origin)),b,?_⟩
    have hid : f (x-(origin+f.symm (cons (head (f (x-origin))) (b • w)))) =
        cons 0 (transverseCoordinate f (x-origin)-b • w) := by
      rw [show x-(origin+f.symm (cons (head (f (x-origin))) (b • w))) =
        (x-origin)-f.symm (cons (head (f (x-origin))) (b • w)) by abel,
        map_sub,f.apply_symm_apply]
      ext i
      cases i using Fin.cases <;> simp [cons,head,tail,transverseCoordinate]
    rw [← f.norm_map _,hid,norm_cons_zero]
    exact hb
  · rintro ⟨a,b,hb⟩
    refine ⟨b,?_⟩
    have h := (transverseCoordinate_norm_le f (x-(origin+f.symm (cons a (b • w))))).trans hb
    simpa [transverseCoordinate,sub_add_eq_sub_sub] using h

/-- The transverse radius is an actual lower bound for distance from every point
of the stem axis. -/
theorem distance_from_stem_lower {k : ℕ} (f : Space (k+1) ≃ₗᵢ[ℝ] Space (k+1))
    (origin x : Space (k+1)) (a : ℝ) :
    ‖transverseCoordinate f (x-origin)‖ ≤ ‖x-(origin+f.symm (cons a 0))‖ := by
  have h := transverseCoordinate_norm_le f (x-(origin+f.symm (cons a 0)))
  simpa [transverseCoordinate,sub_add_eq_sub_sub] using h

/-- There is a closest point on the stem with exactly that transverse distance. -/
theorem exists_stem_point_at_transverse_distance {k : ℕ}
    (f : Space (k+1) ≃ₗᵢ[ℝ] Space (k+1)) (origin x : Space (k+1)) :
    ∃ a : ℝ, ‖x-(origin+f.symm (cons a 0))‖ = ‖transverseCoordinate f (x-origin)‖ := by
  refine ⟨head (f (x-origin)),?_⟩
  rw [← f.norm_map _]
  have hid : f (x-(origin+f.symm (cons (head (f (x-origin))) 0))) =
      cons 0 (transverseCoordinate f (x-origin)) := by
    rw [show x-(origin+f.symm (cons (head (f (x-origin))) 0)) =
      (x-origin)-f.symm (cons (head (f (x-origin))) 0) by abel,
      map_sub,f.apply_symm_apply]
    ext i
    cases i using Fin.cases <;> simp [cons,head,tail,transverseCoordinate]
  rw [hid,norm_cons_zero]

/-- A distant point in a thin plane bin determines the bin's projective normal. -/
theorem plank_direction_cap {k : ℕ} (f : Space (k+1) ≃ₗᵢ[ℝ] Space (k+1))
    (origin x : Space (k+1)) (w : Space k) {err s : ℝ}
    (hw : ‖w‖ = 1) (hs : 0 < s) (hdist : s ≤ ‖transverseCoordinate f (x-origin)‖)
    (hsmall : 2*err ≤ s) (hx : x ∈ plank f origin w err) :
    projectiveDistance w (unitize (transverseCoordinate f (x-origin))) ≤ 4*err/s := by
  obtain ⟨b,hb⟩ := hx
  have hn := norm_sub_le (transverseCoordinate f (x-origin))
    (transverseCoordinate f (x-origin)-b • w)
  have hid : transverseCoordinate f (x-origin)-
      (transverseCoordinate f (x-origin)-b • w) = b • w := by abel
  rw [hid,norm_smul,Real.norm_eq_abs,hw,mul_one] at hn
  have ht := norm_add_le (transverseCoordinate f (x-origin)-b • w) (b • w)
  rw [sub_add_cancel,norm_smul,Real.norm_eq_abs,hw,mul_one] at ht
  have hgap : s/2 ≤ |b| := by linarith
  have h := projective_direction_of_displacement_any (transverseCoordinate f (x-origin)) w hw
    (by linarith : 0 < s/2) hgap hb
  convert h using 1; ring

/-- Plane-bin overlap has exponent ambient-minus-two, by packing on the actual
transverse unit sphere, not by pretending all original tube directions lie there. -/
theorem plane_bin_overlap {ι : Type*} {k : ℕ}
    (f : Space (k+2) ≃ₗᵢ[ℝ] Space (k+2)) (origin x : Space (k+2))
    (bins : Finset ι) (normal : ι → Space (k+1)) {δ C s : ℝ}
    (hδ : 0 < δ) (hC : 1 ≤ C) (hs : 0 < s) (hs1 : s ≤ 1)
    (hdist : s ≤ ‖transverseCoordinate f (x-origin)‖) (hsmall : 2*(C*δ) ≤ s)
    (hunit : ∀ i ∈ bins, ‖normal i‖ = 1)
    (hpoint : ∀ i ∈ bins, x ∈ plank f origin (normal i) (C*δ))
    (hsep : ∀ i ∈ bins, ∀ j ∈ bins, i ≠ j → δ ≤ projectiveDistance (normal i) (normal j)) :
    (bins.card:ℝ) ≤ packingConstant k*(4*C/s)^k := by
  have hcapScale : δ ≤ 4*(C*δ)/s := (le_div_iff₀ hs).mpr (by nlinarith)
  have h := indexed_projective_cap_packing bins normal
    (unitize (transverseCoordinate f (x-origin))) hδ hcapScale hunit
    (fun i hi => plank_direction_cap f origin x (normal i) (hunit i hi) hs hdist hsmall (hpoint i hi)) hsep
  have hid : (4*(C*δ)/s)/δ = 4*C/s := by field_simp
  rwa [hid] at h

/-- Scalar points on projectively nearby lines can be matched with an appropriate
signed scalar, without choosing an orientation globally. -/
theorem scalar_projective_match {k : ℕ} (w v : Space k) (b : ℝ) {δ : ℝ}
    (h : projectiveDistance w v ≤ δ) :
    ∃ a : ℝ, ‖b • w-a • v‖ ≤ |b| *δ := by
  rcases min_le_iff.mp h with hminus | hplus
  · refine ⟨b,?_⟩
    rw [← smul_sub,norm_smul,Real.norm_eq_abs]
    exact mul_le_mul_of_nonneg_left hminus (abs_nonneg b)
  · refine ⟨-b,?_⟩
    have hid : b • w-(-b) • v = b • (w+v) := by module
    rw [hid,norm_smul,Real.norm_eq_abs]
    exact mul_le_mul_of_nonneg_left hplus (abs_nonneg b)

/-- Changing a plane representative by δ changes its location in a bounded ball
by at most δ times its transverse extent. -/
theorem plank_normal_change {k : ℕ} (f : Space (k+1) ≃ₗᵢ[ℝ] Space (k+1))
    (origin x : Space (k+1)) (w v : Space k) {err δ R : ℝ}
    (hw : ‖w‖ = 1) (hδ : 0 ≤ δ) (hnear : projectiveDistance w v ≤ δ)
    (hball : ‖x-origin‖ ≤ R) (hx : x ∈ plank f origin w err) :
    x ∈ plank f origin v (err+(R+err)*δ) := by
  obtain ⟨b,hb⟩ := hx
  have hnorm := norm_sub_le (transverseCoordinate f (x-origin))
    (transverseCoordinate f (x-origin)-b • w)
  have hid : transverseCoordinate f (x-origin)-(transverseCoordinate f (x-origin)-b • w) = b • w := by abel
  rw [hid,norm_smul,Real.norm_eq_abs,hw,mul_one] at hnorm
  have hcoord := (transverseCoordinate_norm_le f (x-origin)).trans hball
  have hbound : |b| ≤ R+err := by linarith
  obtain ⟨a,ha⟩ := scalar_projective_match w v b hnear
  refine ⟨a,?_⟩
  have hsplit : transverseCoordinate f (x-origin)-a • v =
      (transverseCoordinate f (x-origin)-b • w)+(b • w-a • v) := by abel
  rw [hsplit]
  have hm := mul_le_mul_of_nonneg_right hbound hδ
  exact (norm_add_le _ _).trans (by linarith)

/-- A finite actual family of planes admits a separated net whose thickened
planks contain the original planks inside the prescribed bounded region. -/
theorem finite_plane_bins {ι : Type*} {k : ℕ}
    (f : Space (k+2) ≃ₗᵢ[ℝ] Space (k+2)) (origin : Space (k+2))
    (points : Finset ι) (normal : ι → Space (k+1)) {δ C R : ℝ}
    (hδ : 0 < δ) (hδ1 : δ ≤ 1) (hC : 0 ≤ C)
    (hunit : ∀ i ∈ points, ‖normal i‖ = 1) :
    ∃ bins ⊆ points, KakeyaFormal.CapCover.SeparatedOn normal δ bins ∧
      (bins.card:ℝ) ≤ packingConstant k*(1/δ)^k ∧
      ∀ i ∈ points, ∃ j ∈ bins, ∀ x : Space (k+2), ‖x-origin‖ ≤ R →
        x ∈ plank f origin (normal i) (C*δ) → x ∈ plank f origin (normal j) ((2*C+R)*δ) := by
  obtain ⟨bins,hsub,hsep,hcover⟩ := KakeyaFormal.CapCover.finite_projective_net points normal hδ
  refine ⟨bins,hsub,hsep,?_,?_⟩
  · have h := indexed_projective_cap_packing bins normal (0 : Space (k+1)) hδ hδ1
      (fun i hi => hunit i (hsub hi))
      (fun i hi => by simp [projectiveDistance,hunit i (hsub hi)]) hsep
    exact h
  · intro i hi
    obtain ⟨j,hj,hij⟩ := hcover i hi
    refine ⟨j,hj,?_⟩
    intro x hball hx
    obtain ⟨b,hb⟩ := plank_normal_change f origin x (normal i) (normal j)
      (hunit i hi) hδ.le hij.le hball hx
    refine ⟨b,hb.trans ?_⟩
    have hcδ := mul_le_mul_of_nonneg_left hδ1 hC
    nlinarith [mul_le_mul_of_nonneg_right hcδ hδ.le]

/-- Reconstruct a vector from its unitized direction, including the zero case. -/
theorem norm_smul_unitize {k : ℕ} (v : Space k) : ‖v‖ • unitize v = v := by
  by_cases hv : v = 0
  · simp [hv,unitize]
  · rw [unitize,smul_smul,mul_inv_cancel₀ (norm_ne_zero_iff.mpr hv),one_smul]

def bristleNormal {k : ℕ} (stem bristle : UnitTube (k+1)) : Space k :=
  unitize (transverseCoordinate (alignStem stem.direction) bristle.direction)

/-- The actual direction of the stem has zero transverse coordinates in its
explicit Householder frame. -/
theorem stem_transverse_zero {k : ℕ} (stem : UnitTube (k+1)) :
    transverseCoordinate (alignStem stem.direction) stem.direction = 0 := by
  simp [transverseCoordinate,alignStem_apply stem.direction stem.unit_direction,axisUnit]

/-- Every actual bristle meeting the stem lies within 3δ of its actual stem plane.
No planar-containment or line-intersection conclusion is assumed as an input. -/
theorem bristle_in_stem_plank {k : ℕ} (stem bristle : UnitTube (k+1)) {δ : ℝ}
    (hne : (stem.carrier δ ∩ bristle.carrier δ).Nonempty) :
    bristle.carrier δ ⊆ plank (alignStem stem.direction) stem.base (bristleNormal stem bristle) (3*δ) := by
  obtain ⟨p,hpstem,hpbristle⟩ := hne
  obtain ⟨s₀,_,hs₀⟩ := hpstem
  obtain ⟨t₀,_,ht₀⟩ := hpbristle
  let f := alignStem stem.direction
  have hclose : ‖bristle.axisPoint t₀-stem.axisPoint s₀‖ ≤ 2*δ := by
    have htri := dist_triangle (bristle.axisPoint t₀) p (stem.axisPoint s₀)
    have ht' : dist (bristle.axisPoint t₀) p ≤ δ := by simpa only [dist_comm] using ht₀
    change dist (bristle.axisPoint t₀) (stem.axisPoint s₀) ≤ 2*δ
    linarith
  have hcore : ‖transverseCoordinate f (bristle.axisPoint t₀-stem.base)‖ ≤ 2*δ := by
    have hid : bristle.axisPoint t₀-stem.base =
        (bristle.axisPoint t₀-stem.axisPoint s₀)+s₀ • stem.direction := by
      dsimp [UnitTube.axisPoint]
      abel
    rw [hid,transverseCoordinate_add,transverseCoordinate_smul,stem_transverse_zero,smul_zero,add_zero]
    exact (transverseCoordinate_norm_le f _).trans hclose
  intro x hx
  obtain ⟨t,_,ht⟩ := hx
  refine ⟨(t-t₀)*‖transverseCoordinate f bristle.direction‖,?_⟩
  change ‖transverseCoordinate f (x-stem.base)-
    ((t-t₀)*‖transverseCoordinate f bristle.direction‖) •
      unitize (transverseCoordinate f bristle.direction)‖ ≤ 3*δ
  rw [mul_smul,norm_smul_unitize]
  have hid : (x-stem.base)-(t-t₀) • bristle.direction =
      (x-bristle.axisPoint t)+(bristle.axisPoint t₀-stem.base) := by
    dsimp [UnitTube.axisPoint]
    module
  rw [← transverseCoordinate_smul,← transverseCoordinate_sub,hid,transverseCoordinate_add]
  have herror := (transverseCoordinate_norm_le f (x-bristle.axisPoint t)).trans ht
  exact (norm_add_le _ _).trans (by linarith)

/-- Orthogonal maps preserve the actual unoriented chord distance. -/
theorem isometry_projective {k : ℕ} (f : Space k ≃ₗᵢ[ℝ] Space k) (u v : Space k) :
    projectiveDistance (f u) (f v) = projectiveDistance u v := by
  simp only [projectiveDistance,← map_sub,← map_add,f.norm_map]

/-- The first Euclidean coordinate is inner product with the actual unit axis. -/
theorem axis_inner_head {k : ℕ} (v : Space (k+1)) :
    inner ℝ (axisUnit k) v = head v := by
  simp [PiLp.inner_apply,Fin.sum_univ_succ,axisUnit,cons,head]

/-- Nonzero projective angle supplies a quantitatively nonzero transverse vector
in the actual stem frame, with a harmless factor-two chord/sine comparison. -/
theorem stem_transverse_lower {k : ℕ} (stem bristle : UnitTube (k+1)) :
    projectiveDistance stem.direction bristle.direction/2 ≤
      ‖transverseCoordinate (alignStem stem.direction) bristle.direction‖ := by
  let f := alignStem stem.direction
  have hf : f stem.direction = axisUnit k := alignStem_apply stem.direction stem.unit_direction
  have hu : ‖f bristle.direction‖ = 1 := by rw [f.norm_map,bristle.unit_direction]
  have hchord := projective_chord_sq (f stem.direction) (f bristle.direction)
    (by rw [f.norm_map,stem.unit_direction]) hu
  rw [isometry_projective,hf,axis_inner_head] at hchord
  have hsplit := norm_sq_split (f bristle.direction)
  rw [hu,one_pow] at hsplit
  have hh : |head (f bristle.direction)| ≤ 1 := by
    simpa only [head,Real.norm_eq_abs,hu] using PiLp.norm_apply_le (f bristle.direction) 0
  have hab := abs_nonneg (head (f bristle.direction))
  have hs := sq_abs (head (f bristle.direction))
  have hd := projectiveDistance_nonneg stem.direction bristle.direction
  change projectiveDistance stem.direction bristle.direction/2 ≤ ‖tail (f bristle.direction)‖
  nlinarith [mul_nonneg hab (sub_nonneg.mpr hh),norm_nonneg (tail (f bristle.direction))]

/-- A transverse actual bristle has a unit projective-plane representative. -/
theorem bristleNormal_unit {k : ℕ} (stem bristle : UnitTube (k+1))
    (hangle : 0 < projectiveDistance stem.direction bristle.direction) :
    ‖bristleNormal stem bristle‖ = 1 := by
  apply unitize_unit
  have h := stem_transverse_lower stem bristle
  exact norm_pos_iff.mp (by linarith)

/-- Complete finite plane-bin construction for actual transverse bristles meeting
one actual stem. Every bounded-region bristle point lies in its assigned bin. -/
theorem bristle_plane_bins {ι : Type*} {k : ℕ} (stem : UnitTube (k+2))
    (points : Finset ι) (bristle : ι → UnitTube (k+2)) {δ R : ℝ}
    (hδ : 0 < δ) (hδ1 : δ ≤ 1)
    (hangle : ∀ i ∈ points, 0 < projectiveDistance stem.direction (bristle i).direction)
    (hmeet : ∀ i ∈ points, (stem.carrier δ ∩ (bristle i).carrier δ).Nonempty) :
    ∃ bins ⊆ points, KakeyaFormal.CapCover.SeparatedOn
        (fun i => bristleNormal stem (bristle i)) δ bins ∧
      (bins.card:ℝ) ≤ packingConstant k*(1/δ)^k ∧
      ∀ i ∈ points, ∃ j ∈ bins, ∀ x ∈ (bristle i).carrier δ, ‖x-stem.base‖ ≤ R →
        x ∈ plank (alignStem stem.direction) stem.base (bristleNormal stem (bristle j)) ((6+R)*δ) := by
  obtain ⟨bins,hsub,hsep,hcount,hcover⟩ := finite_plane_bins (alignStem stem.direction)
    stem.base points (fun i => bristleNormal stem (bristle i)) (C := (3:ℝ)) (R := R)
    hδ hδ1 (by norm_num) (fun i hi => bristleNormal_unit stem (bristle i) (hangle i hi))
  refine ⟨bins,hsub,hsep,hcount,?_⟩
  intro i hi
  obtain ⟨j,hj,hjcover⟩ := hcover i hi
  refine ⟨j,hj,?_⟩
  intro x hx hball
  have hp := bristle_in_stem_plank stem (bristle i) (hmeet i hi) hx
  simpa only [show (2:ℝ)*3 = 6 by norm_num] using hjcover x hball hp

end
end KakeyaFormal.HairbrushPlanes

#print axioms KakeyaFormal.HairbrushPlanes.plane_bin_overlap
#print axioms KakeyaFormal.HairbrushPlanes.bristle_plane_bins
